# Generated by Django 4.2.6 on 2023-11-06 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Culture",
            fields=[
                ("Id_culture", models.AutoField(primary_key=True, serialize=False)),
                ("Nom", models.CharField(max_length=100)),
            ],
            options={"db_table": "Culture",},
        ),
        migrations.CreateModel(
            name="Donnees",
            fields=[
                ("Id_donnees", models.AutoField(primary_key=True, serialize=False)),
                ("Titre", models.CharField(max_length=50)),
                ("Description", models.CharField(max_length=500)),
                ("Date_donnees", models.DateField()),
                ("Date_enregistrement", models.DateField(auto_now=True)),
                ("Fichier", models.FileField(upload_to="data")),
            ],
            options={"db_table": "Donnees",},
        ),
        migrations.CreateModel(
            name="Periode",
            fields=[
                ("Id_periode", models.AutoField(primary_key=True, serialize=False)),
                ("Debut", models.DateField()),
                ("Fin", models.DateField()),
            ],
            options={"db_table": "Periode",},
        ),
        migrations.CreateModel(
            name="SuperUtilisateur",
            fields=[
                ("Id_utilisateur", models.AutoField(primary_key=True, serialize=False)),
                ("Prenom", models.CharField(max_length=50)),
                ("Nom", models.CharField(max_length=50)),
                ("Email", models.EmailField(max_length=250, unique=True)),
                ("Mot_de_passe", models.CharField(max_length=50)),
                ("Confirme_MDP", models.CharField(max_length=50)),
            ],
            options={"db_table": "SuperUtilisateur",},
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                ("Id_region", models.AutoField(primary_key=True, serialize=False)),
                ("Nom", models.CharField(max_length=100)),
                ("Cultures", models.ManyToManyField(to="asa_app.culture")),
            ],
            options={"db_table": "Region",},
        ),
        migrations.AddField(
            model_name="culture",
            name="Periodes",
            field=models.ManyToManyField(to="asa_app.periode"),
        ),
    ]
